spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    auto-commit: false
    url: jdbc:mysql://45.76.156.122:3306/bhs_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: bhs_user
    password: Abc123456@
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  mail:
    host: smtp.gmail.com
    port:  587
    username: bhsmailsender@gmail.com
    password: Abc123456@
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

application: 
  mail:
    base-url: http://207.148.124.83:3001
    from: bhsmailsender@gmail.com
  cors:
    allowed-origins: "http://207.148.124.83:3000,http://207.148.124.83:3001,http://localhost:3000,http://127.0.0.1:3000,http://45.76.156.122:3000,http://45.76.156.122:3001,http://bhs-admin.x70s.com,http://bhs.x70s.com"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count,X-bhs-error,X-bhs-alert"
    allow-credentials: true
    max-age: 1800
    

server:
  port: 8080